main_mbti_type/urls.py
from django.urls import path
from .views import index, mbti_detail

app_name = "main_page"

urlpatterns = [
    path("", index, name="index"),
    path("mbti/<str:type_name>/", mbti_detail, name="mbti_detail"),
]

mbti_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("main_mbti_type.urls", namespace="main_page")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

main_mbti_type/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class MBTIType(models.Model):
    type_name = models.CharField(max_length=4)
    type_description = models.TextField()
    type_image = models.ImageField(upload_to="images/")
    traits = models.TextField(default="", blank=True, null=True)
    hard_facts = models.TextField(default="", blank=True, null=True)

    def __str__(self):
        return self.type_name

# class Compatibility(models.Model):
#     mbti_type1 = models.ForeignKey(
#         MBTIType,
#         related_name = "compatibility_type1",
#         on_delete=models.CASCADE
#     )
#     mbti_type2 = models.ForeignKey(
#         MBTIType,
#         related_name = "compatibility_type2",
#         on_delete=models.CASCADE
#     )
#     compatibility_score = models.IntegersField()

main_mbti_type/views.py
from django.shortcuts import render, get_object_or_404, redirect
from main_mbti_type.models import MBTIType
# Create your views here.

def calculate_compatibility(type1, type2):
    error_message = None
    compatibility_chart = {
        "INFP": {"INFP":"GOOD", "ENFP":"GOOD", "INFJ":"GOOD", "ENFJ":"PERFECT", "INTJ":"GOOD", "ENTJ":"PERFECT", "INTP":"GOOD", "ENTP":"GOOD", "ISFP":"BAD", "ESFP":"BAD", "ISTP":"BAD", "ESTP":"BAD", "ISFJ":"BAD", "ESFJ":"BAD", "ISTJ":"BAD", "ESTJ": "BAD"},
        "ENFP": {"INFP":"GOOD", "ENFP":"GOOD", "INFJ":"PERFECT", "ENFJ":"GOOD", "INTJ":"PERFECT", "ENTJ":"GOOD", "INTP":"GOOD", "ENTP":"GOOD", "ISFP":"BAD", "ESFP":"BAD", "ISTP":"BAD", "ESTP":"BAD", "ISFJ":"BAD", "ESFJ":"BAD", "ISTJ":"BAD", "ESTJ": "BAD"},
        "INFJ": {"INFP":"GOOD", "ENFP":"PERFECT", "INFJ":"GOOD", "ENFJ":"GOOD", "INTJ":"GOOD", "ENTJ":"GOOD", "INTP":"GOOD", "ENTP":"PERFECT", "ISFP":"BAD", "ESFP":"BAD", "ISTP":"BAD", "ESTP":"BAD", "ISFJ":"BAD", "ESFJ":"BAD", "ISTJ":"BAD", "ESTJ": "BAD"},
        "ENFJ": {"INFP":"PERFECT", "ENFP":"GOOD", "INFJ":"GOOD", "ENFJ":"GOOD", "INTJ":"GOOD", "ENTJ":"GOOD", "INTP":"GOOD", "ENTP":"GOOD", "ISFP":"PERFECT", "ESFP":"BAD", "ISTP":"BAD", "ESTP":"BAD", "ISFJ":"BAD", "ESFJ":"BAD", "ISTJ":"BAD", "ESTJ": "BAD"},
        "INTJ": {"INFP":"GOOD", "ENFP":"PERFECT", "INFJ":"GOOD", "ENFJ":"GOOD", "INTJ":"GOOD", "ENTJ":"GOOD", "INTP":"GOOD", "ENTP":"PERFECT", "ISFP":"AVERAGE", "ESFP":"AVERAGE", "ISTP":"AVERAGE", "ESTP":"AVERAGE", "ISFJ":"POOR", "ESFJ":"POOR", "ISTJ":"POOR", "ESTJ": "POOR"},
        "ENTJ": {"INFP":"PERFECT", "ENFP":"GOOD", "INFJ":"GOOD", "ENFJ":"GOOD", "INTJ":"GOOD", "ENTJ":"GOOD", "INTP":"PERFECT", "ENTP":"GOOD", "ISFP":"AVERAGE", "ESFP":"AVERAGE", "ISTP":"AVERAGE", "ESTP":"AVERAGE", "ISFJ":"AVERAGE", "ESFJ":"AVERAGE", "ISTJ":"AVERAGE", "ESTJ": "AVERAGE"},
        "INTP": {"INFP":"GOOD", "ENFP":"GOOD", "INFJ":"GOOD", "ENFJ":"GOOD", "INTJ":"GOOD", "ENTJ":"PERFECT", "INTP":"GOOD", "ENTP":"GOOD", "ISFP":"AVERAGE", "ESFP":"AVERAGE", "ISTP":"AVERAGE", "ESTP":"AVERAGE", "ISFJ":"POOR", "ESFJ":"POOR", "ISTJ":"POOR", "ESTJ": "PERFECT"},
        "ENTP": {"INFP":"GOOD", "ENFP":"GOOD", "INFJ":"PERFECT", "ENFJ":"GOOD", "INTJ":"PERFECT", "ENTJ":"GOOD", "INTP":"GOOD", "ENTP":"GOOD", "ISFP":"AVERAGE", "ESFP":"AVERAGE", "ISTP":"AVERAGE", "ESTP":"AVERAGE", "ISFJ":"POOR", "ESFJ":"POOR", "ISTJ":"POOR", "ESTJ": "POOR"},
        "ISFP": {"INFP":"BAD", "ENFP":"BAD", "INFJ":"BAD", "ENFJ":"PERFECT", "INTJ":"AVERAGE", "ENTJ":"AVERAGE", "INTP":"AVERAGE", "ENTP":"AVERAGE", "ISFP":"POOR", "ESFP":"POOR", "ISTP":"POOR", "ESTP":"POOR", "ISFJ":"AVERAGE", "ESFJ":"PERFECT", "ISTJ":"AVERAGE", "ESTJ": "PERFECT"},
        "ESFP": {"INFP":"BAD", "ENFP":"BAD", "INFJ":"BAD", "ENFJ":"BAD", "INTJ":"AVERAGE", "ENTJ":"AVERAGE", "INTP":"AVERAGE", "ENTP":"AVERAGE", "ISFP":"POOR", "ESFP":"POOR", "ISTP":"POOR", "ESTP":"POOR", "ISFJ":"PERFECT", "ESFJ":"AVERAGE", "ISTJ":"PERFECT", "ESTJ": "AVERAGE"},
        "ISTP": {"INFP":"BAD", "ENFP":"BAD", "INFJ":"BAD", "ENFJ":"BAD", "INTJ":"AVERAGE", "ENTJ":"AVERAGE", "INTP":"AVERAGE", "ENTP":"AVERAGE", "ISFP":"POOR", "ESFP":"POOR", "ISTP":"POOR", "ESTP":"POOR", "ISFJ":"AVERAGE", "ESFJ":"PERFECT", "ISTJ":"AVERAGE", "ESTJ": "PERFECT"},
        "ESTP": {"INFP":"BAD", "ENFP":"BAD", "INFJ":"BAD", "ENFJ":"BAD", "INTJ":"AVERAGE", "ENTJ":"AVERAGE", "INTP":"AVERAGE", "ENTP":"AVERAGE", "ISFP":"POOR", "ESFP":"POOR", "ISTP":"POOR", "ESTP":"POOR", "ISFJ":"PERFECT", "ESFJ":"AVERAGE", "ISTJ":"PERFECT", "ESTJ": "AVERAGE"},
        "ISFJ": {"INFP":"BAD", "ENFP":"BAD", "INFJ":"BAD", "ENFJ":"BAD", "INTJ":"POOR", "ENTJ":"AVERAGE", "INTP":"POOR", "ENTP":"POOR", "ISFP":"AVERAGE", "ESFP":"PERFECT", "ISTP":"AVERAGE", "ESTP":"PERFECT", "ISFJ":"GOOD", "ESFJ":"GOOD", "ISTJ":"GOOD", "ESTJ": "GOOD"},
        "ESFJ": {"INFP":"BAD", "ENFP":"BAD", "INFJ":"BAD", "ENFJ":"BAD", "INTJ":"POOR", "ENTJ":"AVERAGE", "INTP":"POOR", "ENTP":"POOR", "ISFP":"PERFECT", "ESFP":"AVERAGE", "ISTP":"PERFECT", "ESTP":"AVERAGE", "ISFJ":"GOOD", "ESFJ":"GOOD", "ISTJ":"GOOD", "ESTJ": "GOOD"},
        "ISTJ": {"INFP":"BAD", "ENFP":"BAD", "INFJ":"BAD", "ENFJ":"BAD", "INTJ":"POOR", "ENTJ":"AVERAGE", "INTP":"POOR", "ENTP":"POOR", "ISFP":"AVERAGE", "ESFP":"PERFECT", "ISTP":"AVERAGE", "ESTP":"PERFECT", "ISFJ":"GOOD", "ESFJ":"GOOD", "ISTJ":"GOOD", "ESTJ": "GOOD"},
        "ESTJ": {"INFP":"BAD", "ENFP":"BAD", "INFJ":"BAD", "ENFJ":"BAD", "INTJ":"POOR", "ENTJ":"AVERAGE", "INTP":"PERFECT", "ENTP":"POOR", "ISFP":"PERFECT", "ESFP":"AVERAGE", "ISTP":"PERFECT", "ESTP":"AVERAGE", "ISFJ":"GOOD", "ESFJ":"GOOD", "ISTJ":"GOOD", "ESTJ": "GOOD"}
        }
    if len(type1) < 4 or len(type2) < 4:
        error_message = "Please enter a valid MBTI type consisting of 4 letters. You can take the MBTI test using the link above"
        return error_message
    elif type1 not in compatibility_chart or type2 not in compatibility_chart:
        error_message = "Please enter a valid MBTI type. You can take the MBTI test using the link above"
        return error_message
    else:
        return compatibility_chart[type1][type2]

def index(request):
    mbti_types = MBTIType.objects.all()

    if request.method == "POST":
        type1 = request.POST.get("type1")
        type2 = request.POST.get("type2")
        compatibility_score = calculate_compatibility(type1, type2)
        context = {
            "mbti_types": mbti_types,
            "type1": type1,
            "type2": type2,
            "compatibility_score": compatibility_score
        }
        return render(request, "main_mbti_type/index.html", context)
    context = {'mbti_types': mbti_types}
    return render(request, 'main_mbti_type/index.html', context)


def mbti_detail(request, type_name):
    mbti_type = get_object_or_404(MBTIType, type_name=type_name)
    hard_fact_list = mbti_type.hard_facts.split('\n')
    context = {
        "mbti_type": mbti_type,
        "hard_fact_list": hard_fact_list
        }
    return render(request, "main_mbti_type/detail.html", context)




# green- good4
# blue - perfect5
# yellow - poor2
# light green - average 3
# red- bad1

main_mbti_type/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock title %}
    </title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <nav>
        <a href='{% url "main_page:index" %}'>Main Page</a>
        <p></p>
        <a href="https://www.16personalities.com/personality-types">Take the Myers–Briggs Type Indicator Test</a>
    </nav>
</head>
<body>
    {% block content %}{% endblock content %}

</body>

</html>

main_mbti_type/templates/main_mbti_type/detail.html
{% extends "base.html" %}

{% block title %}
    {{ mbti_type.type_name }} Detail Page
{% endblock title %}

{% block content %}
<main>
        <div id="mbti-detail">
            <h2>{{ mbti_type.type_name }}</h2>
            {% if mbti_type.type_image %}
                <img src="{{ mbti_type.type_image.url }}" alt="{{ mbti_type.type_name }}">
            {% endif %}
            <p>{{ mbti_type.type_description }}</p>
        </div>
        <ul id="hard_facts">
            {% for hard_fact in hard_fact_list %}
                <li>{{ hard_fact }}</li>
            {% endfor %}
        </ul>
</main>
{% endblock content %}


{% comment %} {{ mbti_type.hard_facts }} {% endcomment %}

main_mbti_type/templates/main_mbti_type/index.html
{% extends "base.html" %}
{% include 'main_mbti_type/table.html' %}
{% load static %}

{% block title %}
    Main Page
{% endblock title %}

{% block content %}
<p>
    Calculate MBTI Compatibility
    <div>
        <form method="post">
            {% csrf_token %}
            <label for="type1">Input MBTI Type 1:</label>
            <input type="text" name="type1" id="type1" oninput="this.value = this.value.toUpperCase()" maxlength="4">
            <label for="type2">Input MBTI Type 2:</label>
            <input type="text" name="type2" id="type2" oninput="this.value = this.value.toUpperCase()" maxlength="4">
            <button type="submit">Calculate Compatibility</button>
            {% if compatibility_score is not None %}
            <p>Compatibility Score for "{{ type1 }}" and "{{ type2 }}": {{ compatibility_score }}</p>
            <div class=key>
                <p>Key:</p>
                <p>
                "Perfect": Ideal Match, yall better start cookin something<br>
                "Good": Pretty Good, Just put in the work<br>
                "Average": You guys don't really hate each other<br>
                "Poor": It cannnnn work, but why?<br>
                "Bad": Straight up not going to work<br>
                </p>
            </div>
            {% else %}
                {% if error_message %}
                    <p>{{ error_message }}</p><br>
                    <p>Please input MBTI Type 1 and Type 2 to calculate compatibility.</p>
            {% endif %}
            {% endif %}
        </form>
    </div>
</p>
<p>
    <table>
        <tr>
          <th>Personality Trait</th>
          <th>Description</th>
        </tr>
        <tr>
          <td>Introversion</td>
          <td>Gains energy from being alone</td>
        </tr>
        <tr>
          <td>Extroversion</td>
          <td>Gains energy from being with others</td>
        </tr>
        <tr>
          <td>iNtuition</td>
          <td>Focuses on the future, imaginative</td>
        </tr>
        <tr>
          <td>Sensing</td>
          <td>Focuses on the present, values experience</td>
        </tr>
        <tr>
          <td>Feeling</td>
          <td>Makes decisions based on emotions</td>
        </tr>
        <tr>
          <td>Thinking</td>
          <td>Makes decisions based on logic</td>
        </tr>
        <tr>
          <td>Perceiving</td>
          <td>Adapts to situations as they arise</td>
        </tr>
        <tr>
          <td>Judging</td>
          <td>Prefers to plan ahead</td>
        </tr>
      </table>
</p>
<main>
    {% for mbti_type in mbti_types %}
        <div class="mbti-detail">
            <h2><a href="{% url 'main_page:mbti_detail' type_name=mbti_type.type_name %}">{{ mbti_type.type_name }}</a></h2>
            {% if mbti_type.type_image %}
                <img src="{{ mbti_type.type_image.url }}" alt="{{ mbti_type.type_name }}">
            {% endif %}
            <p>{{ mbti_type.traits }}</p>
        </div>
    {% endfor %}
</main>
<footer>
 <div id="footer">
        <img src="{% static "images/christian-singles.jpeg" %}" alt="Christian Singles">
        <button id="close-btn">X</button>
    </div>
</footer>


{% comment %} <footer class="footer">
    <p><img src="{% static "images/christian-singles.jpeg" %}" alt="Christian Singles"></p>
</footer> {% endcomment %}
{% endblock content %}

{% comment %} <h2><a href="{% url 'mbti_detail' type_name=mbti_type.type_name %}">{{ mbti_type.type_name }}</a></h2> {% endcomment %}
{% comment %} <a href="{% url 'mbti_detail' mbti_type.type_name %}"> {% endcomment %}

main_mbti_type/templates/main_mbti_type/table.html
<table>
    <tr>
      <th>Personality Trait</th>
      <th>Description</th>
    </tr>
    <tr>
      <td>Introversion</td>
      <td>Gains energy from being alone</td>
    </tr>
    <tr>
      <td>Extroversion</td>
      <td>Gains energy from being with others</td>
    </tr>
    <tr>
      <td>Intuition</td>
      <td>Focuses on the future, imaginative</td>
    </tr>
    <tr>
      <td>Sensing</td>
      <td>Focuses on the present, values experience</td>
    </tr>
    <tr>
      <td>Feeling</td>
      <td>Makes decisions based on emotions</td>
    </tr>
    <tr>
      <td>Thinking</td>
      <td>Makes decisions based on logic</td>
    </tr>
    <tr>
      <td>Perceiving</td>
      <td>Adapts to situations as they arise</td>
    </tr>
    <tr>
      <td>Judging</td>
      <td>Prefers to plan ahead</td>
    </tr>
  </table>